# This file is for shared environment 
# ie for common env
# This file is for the same env for dev and prod 
# we can overwrite the env in dev and prod files
# this is for common env for both dev and prod
# this is the base docker-compose file
version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mahesh
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    # named volume for the database
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    
# now this db folder can be used by other containers also ie now it is persistent 
volumes:
  mongo-db: